opt_in_rules:
    - closure_spacing
    - empty_count
    - fatal_error_message
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - prohibited_super_call
    - vertical_parameter_alignment_on_call
    
excluded:
    - Carthage
    - Pods
    - SwiftLint/Common/3rdPartyLib
    
disabled_rules:
    - trailing_whitespace
    - identifier_name

nesting:
    type_level:
        warning: 2

included:
    - NeumorphicUI-Demo
    - ../Sources/NeumorphicUI
    
line_length:
    warning: 190
    error: 220
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    
function_body_length:
    warning: 300
    error: 500
    
function_parameter_count:
    warning: 6
    error: 8

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

type_body_length:
    warning: 600
    error: 1000
    
cyclomatic_complexity:
    warning: 15
    error: 25

identifier_name:
    min_length:
        warning: 1

reporter: "xcode"

